name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu
    environment: github-pages  # Set environment here at the job level

    steps:
      # Step 1: Check out the repository's code
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Set up Node.js (or the necessary environment for your project)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify your Node.js version

      # Step 3: Install dependencies and build the project
      - name: Install dependencies and build
        run: |
          npm install
          npm run build  # Replace with your specific build command if different

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub's token for authentication
          publish_dir: ./public  # Replace with your build output directory
